var Canvas=new Object();Canvas.Drawing=function(_name,_width,_height,_color){this.name=_name;this.width=_width;this.height=_height;if(_color!=undefined)this.color=_color;document.writeln("<canvas id=\""+this.name+"\" style=\"background-color:"+this.color+";\" width=\""+this.width+"\" height=\""+this.height+"\"></canvas>");this.context=document.getElementById(this.name).getContext('2d');this.mousex=undefined;this.mousey=undefined;this.context.canvas.onmouseup=function(){}
this.context.canvas.onmousedown=function(){}
this.context.canvas.onmousemove=function(){}
this.animation=new Object();this.animation.framerate=12;this.animation.start=function(_callback){this.stop();this.interval=setInterval(_callback,1000/this.framerate);}
this.animation.stop=function(){clearInterval(this.interval);}
this.scene=new Object();this.add=function(name,obj){this.scene[name]=obj;this.scene[name].context=this.context;}
this.remove=function(name){delete this.scene[name];}
this.draw=function(){this.context.clearRect(0,0,this.width,this.height);for(var object in this.scene){this.scene[object].draw();}}}
Canvas.Palette=new Object();Canvas.Palette.defaults=new Object();Canvas.Palette.defaults.stroke=new Object();Canvas.Palette.defaults.stroke.color="MidnightBlue";Canvas.Palette.defaults.stroke.width=3;Canvas.Palette.defaults.stroke.cap="butt";Canvas.Palette.defaults.fill="LightGrey";Canvas.Palette.defaults.close=false;Canvas.Palette.common=new Object();Canvas.Palette.common.setDefaults=function(_that){for(var _default in Canvas.Palette.defaults)_that[_default]=Canvas.Palette.defaults[_default];if(_that instanceof Canvas.Palette.Circle){_that.start=0;_that.end=360;_that.clockwise=true;}}
Canvas.Palette.common.setStyle=function(_that){_that.context.strokeStyle=_that.stroke.color;_that.context.lineWidth=_that.stroke.width;var _fill=_that.fill;if(_fill instanceof Canvas.Palette.Gradient){_fill._parent=_that;_fill=_fill.draw();delete _fill._parent;}
_that.context.fillStyle=_fill;_that.context.lineCap=_that.stroke.cap;}
Canvas.Palette.Line=function(_x1,_y1,_x2,_y2){Canvas.Palette.common.setDefaults(this);if((_x1&&_y1&&_x2&&_y2)!=undefined){this.x1=_x1;this.y1=_y1;this.x2=_x2;this.y2=_y2;}}
Canvas.Palette.Line.prototype.draw=function(){Canvas.Palette.common.setStyle(this);this.context.beginPath();this.context.moveTo(this.x1,this.y1);this.context.lineTo(this.x2,this.y2);this.context.stroke();}
Canvas.Palette.Rectangle=function(_x,_y,_width,_height){Canvas.Palette.common.setDefaults(this);if((_x&&_y&&_width&&_height)!=undefined){this.x=_x;this.y=_y;this.width=_width;this.height=_height;}}
Canvas.Palette.Rectangle.prototype.draw=function(){Canvas.Palette.common.setStyle(this);this.context.fillRect(this.x,this.y,this.width,this.height);this.context.strokeRect(this.x,this.y,this.width,this.height);}
Canvas.Palette.Circle=function(_x,_y,_radius){Canvas.Palette.common.setDefaults(this);if((_x&&_y&&_radius)!=undefined){this.x=_x;this.y=_y;this.radius=_radius;}}
Canvas.Palette.Circle.prototype.draw=function(){Canvas.Palette.common.setStyle(this);this.context.beginPath();this.context.arc(this.x,this.y,this.radius,this.start,this.end*Math.PI/180,this.clockwise);if(this.close==true)this.context.closePath();this.context.fill();this.context.stroke();}
Canvas.Palette.Arc=function(_x1,_y1,_x2,_y2,_x3,_y3,_radius){Canvas.Palette.common.setDefaults(this);if((_x1&&_y1&&_x2&&_y2&&_x3&&_y3&&_radius)!=undefined){this.x1=_x1;this.y1=_y1;this.x2=_x2;this.y2=_y2;this.x3=_x3;this.y3=_y3;this.radius=_radius;}}
Canvas.Palette.Arc.prototype.draw=function(){Canvas.Palette.common.setStyle(this);this.context.beginPath();this.context.moveTo(this.x1,this.y1);this.context.arcTo(this.x2,this.y2,this.x3,this.y3,this.radius);this.context.lineTo(this.x3,this.y3);if(this.close==true)this.context.closePath();this.context.fill();this.context.stroke();}
Canvas.Palette.Bezier=function(_x1,_y1,_x2,_y2,_c_x1,_c_y1,_c_x2,_c_y2){Canvas.Palette.common.setDefaults(this);if((_x1&&_y1&&_x2&&_y2)!=undefined){this.x1=_x1;this.y1=_y1;this.x2=_x2;this.y2=_y2;this.c_x1=_c_x1;this.c_y1=_c_y1;this.c_x2=_c_x2;this.c_y2=_c_y2;}}
Canvas.Palette.Bezier.prototype.draw=function(){Canvas.Palette.common.setStyle(this);this.context.beginPath();this.context.moveTo(this.x1,this.y1);this.context.bezierCurveTo(this.c_x1,this.c_y1,this.c_x2,this.c_y2,this.x2,this.y2);if(this.close==true)this.context.closePath();this.context.fill();this.context.stroke();}
Canvas.Palette.Gradient=function(_x1,_y1,_x2,_y2){if((_x1&&_y1&&_x2&&_y2)!=undefined){this.x1=_x1;this.y1=_y1;this.x2=_x2;this.y2=_y2;}
this.stops=new Array();this.addStop=function(_offset,_color){var stop=new Object();stop.offset=_offset;stop.color=_color;this.stops.push(stop);}}
Canvas.Palette.Gradient.prototype.draw=function(){var _x1=this._parent.x+this.x1;var _y1=this._parent.y+this.y1;var _x2=this._parent.x+this.x2;var _y2=this._parent.y+this.y2;var _gradient=this._parent.context.createLinearGradient(_x1,_y1,_x2,_y2);for(var stop in this.stops)
_gradient.addColorStop(this.stops[stop].offset,this.stops[stop].color);return _gradient;}