







/*Generated by jGrouseDoc*/
(function()
{
    var data = [        
       {
           localName : "GLOBAL",
           fullName : "GLOBAL",
           summary : "namespace GLOBAL",
           ref : "logical/GLOBAL.html",
           parent : "",
           type : "namespace",
           elementType : "logical_container"
       } ,         
       {
           localName : "MyClass",
           fullName : "MyClass",
           summary : "class MyClass",
           ref : "logical/MyClass.html",
           parent : "GLOBAL",
           type : "class",
           elementType : "logical_container"
       } ,         
       {
           localName : "innerClass",
           fullName : "MyClass.innerClass",
           summary : "class innerClass",
           ref : "logical/MyClass/innerClass.html",
           parent : "MyClass",
           type : "class",
           elementType : "logical_container"
       } ,         
       {
           localName : "innerInterface",
           fullName : "MyClass.innerInterface",
           summary : "interface innerInterface",
           ref : "logical/MyClass/innerInterface.html",
           parent : "MyClass",
           type : "interface",
           elementType : "logical_container"
       } ,         
       {
           localName : "innerStruct",
           fullName : "MyClass.innerStruct",
           summary : "struct innerStruct",
           ref : "logical/MyClass/innerStruct.html",
           parent : "MyClass",
           type : "struct",
           elementType : "logical_container"
       } ,         
       {
           localName : "MyInterface",
           fullName : "MyInterface",
           summary : "interface MyInterface",
           ref : "logical/MyInterface.html",
           parent : "GLOBAL",
           type : "interface",
           elementType : "logical_container"
       } ,         
       {
           localName : "innerClass",
           fullName : "MyInterface.innerClass",
           summary : "class innerClass",
           ref : "logical/MyInterface/innerClass.html",
           parent : "MyInterface",
           type : "class",
           elementType : "logical_container"
       } ,         
       {
           localName : "innerInterface",
           fullName : "MyInterface.innerInterface",
           summary : "interface innerInterface",
           ref : "logical/MyInterface/innerInterface.html",
           parent : "MyInterface",
           type : "interface",
           elementType : "logical_container"
       } ,         
       {
           localName : "innerStruct",
           fullName : "MyInterface.innerStruct",
           summary : "struct innerStruct",
           ref : "logical/MyInterface/innerStruct.html",
           parent : "MyInterface",
           type : "struct",
           elementType : "logical_container"
       } ,         
       {
           localName : "MyKeyClass",
           fullName : "MyKeyClass",
           summary : "class MyKeyClass",
           ref : "logical/MyKeyClass.html",
           parent : "GLOBAL",
           type : "class",
           elementType : "logical_container"
       } ,         
       {
           localName : "MyObject",
           fullName : "MyObject",
           summary : "object MyObject",
           ref : "logical/MyObject.html",
           parent : "GLOBAL",
           type : "object",
           elementType : "logical_container"
       } ,         
       {
           localName : "addListener",
           fullName : "MyObject.addListener",
           summary : "function addListener(Number event, listenerCallbackSimple callback)\naddListener(Number event, listenerCallbackComplex callback)",
           ref : "logical/MyObject.html#___addListener",
           parent : "MyObject",
           type : "function",
           elementType : "function"
       } ,         
       {
           localName : "createDateFormatter",
           fullName : "MyObject.createDateFormatter",
           summary : "function formatter createDateFormatter(String formatString)",
           ref : "logical/MyObject.html#___createDateFormatter",
           parent : "MyObject",
           type : "function",
           elementType : "function"
       } ,         
       {
           localName : "formatter",
           fullName : "MyObject.formatter",
           summary : "ifunction String formatter(Date date)",
           ref : "logical/MyObject.html#___formatter",
           parent : "MyObject",
           type : "ifunction",
           elementType : "function"
       } ,         
       {
           localName : "listenerCallbackComplex",
           fullName : "MyObject.listenerCallbackComplex",
           summary : "ifunction Boolean listenerCallbackComplex(MyObject obj)",
           ref : "logical/MyObject.html#___listenerCallbackComplex",
           parent : "MyObject",
           type : "ifunction",
           elementType : "function"
       } ,         
       {
           localName : "listenerCallbackSimple",
           fullName : "MyObject.listenerCallbackSimple",
           summary : "ifunction listenerCallbackComplex listenerCallbackSimple(firstParam, String secondParam)",
           ref : "logical/MyObject.html#___listenerCallbackSimple",
           parent : "MyObject",
           type : "ifunction",
           elementType : "function"
       } ,         
       {
           localName : "onReady",
           fullName : "MyObject.onReady",
           summary : "event Boolean onReady(Window window)",
           ref : "logical/MyObject.html#___onReady",
           parent : "MyObject",
           type : "event",
           elementType : "function"
       } ,         
       {
           localName : "MyStruct",
           fullName : "MyStruct",
           summary : "struct MyStruct",
           ref : "logical/MyStruct.html",
           parent : "GLOBAL",
           type : "struct",
           elementType : "logical_container"
       } ,         
       {
           localName : "innerClass",
           fullName : "MyStruct.innerClass",
           summary : "class innerClass",
           ref : "logical/MyStruct/innerClass.html",
           parent : "MyStruct",
           type : "class",
           elementType : "logical_container"
       } ,         
       {
           localName : "innerInterface",
           fullName : "MyStruct.innerInterface",
           summary : "interface innerInterface",
           ref : "logical/MyStruct/innerInterface.html",
           parent : "MyStruct",
           type : "interface",
           elementType : "logical_container"
       } ,         
       {
           localName : "innerStruct",
           fullName : "MyStruct.innerStruct",
           summary : "struct innerStruct",
           ref : "logical/MyStruct/innerStruct.html",
           parent : "MyStruct",
           type : "struct",
           elementType : "logical_container"
       } ,         
       {
           localName : "MyValueClass",
           fullName : "MyValueClass",
           summary : "class MyValueClass",
           ref : "logical/MyValueClass.html",
           parent : "GLOBAL",
           type : "class",
           elementType : "logical_container"
       } ,         
       {
           localName : "add",
           fullName : "add",
           summary : "public static function int add(int first, [int second])",
           ref : "logical/GLOBAL.html#___add",
           parent : "GLOBAL",
           type : "function",
           elementType : "function"
       } ,         
       {
           localName : "com",
           fullName : "com",
           summary : "namespace com",
           ref : "logical/com.html",
           parent : "GLOBAL",
           type : "namespace",
           elementType : "logical_container"
       } ,         
       {
           localName : "foo",
           fullName : "com.foo",
           summary : "namespace foo",
           ref : "logical/com/foo.html",
           parent : "com",
           type : "namespace",
           elementType : "logical_container"
       } ,         
       {
           localName : "bar",
           fullName : "com.foo.bar",
           summary : "namespace bar",
           ref : "logical/com/foo/bar.html",
           parent : "com.foo",
           type : "namespace",
           elementType : "logical_container"
       } ,         
       {
           localName : "Class1",
           fullName : "com.foo.bar.Class1",
           summary : "class Class1",
           ref : "logical/com/foo/bar/Class1.html",
           parent : "com.foo.bar",
           type : "class",
           elementType : "logical_container"
       } ,         
       {
           localName : "Class2",
           fullName : "com.foo.bar.Class2",
           summary : "class Class2",
           ref : "logical/com/foo/bar/Class2.html",
           parent : "com.foo.bar",
           type : "class",
           elementType : "logical_container"
       } ,         
       {
           localName : "InnerClass",
           fullName : "com.foo.bar.Class2.InnerClass",
           summary : "class InnerClass",
           ref : "logical/com/foo/bar/Class2/InnerClass.html",
           parent : "com.foo.bar.Class2",
           type : "class",
           elementType : "logical_container"
       } ,         
       {
           localName : "bla",
           fullName : "com.foo.bla",
           summary : "namespace bla",
           ref : "logical/com/foo/bla.html",
           parent : "com.foo",
           type : "namespace",
           elementType : "logical_container"
       } ,         
       {
           localName : "Object1",
           fullName : "com.foo.bla.Object1",
           summary : "object Object1",
           ref : "logical/com/foo/bla/Object1.html",
           parent : "com.foo.bla",
           type : "object",
           elementType : "logical_container"
       } ,         
       {
           localName : "myEvent",
           fullName : "com.foo.bla.Object1.myEvent",
           summary : "event myEvent(int hitCount, string propertyName)",
           ref : "logical/com/foo/bla/Object1.html#___myEvent",
           parent : "com.foo.bla.Object1",
           type : "event",
           elementType : "function"
       } ,         
       {
           localName : "sampleVar",
           fullName : "com.foo.bla.Object1.sampleVar",
           summary : "variable int sampleVar",
           ref : "logical/com/foo/bla/Object1.html#___sampleVar",
           parent : "com.foo.bla.Object1",
           type : "variable",
           elementType : "variable"
       } ,         
       {
           localName : "getValues",
           fullName : "getValues",
           summary : "function MyValueClass[] getValues(MyValueClass[MyKeyClass] map)",
           ref : "logical/GLOBAL.html#___getValues",
           parent : "GLOBAL",
           type : "function",
           elementType : "function"
       } ,         
       {
           localName : "jbooze",
           fullName : "jbooze",
           summary : "namespace jbooze",
           ref : "logical/jbooze.html",
           parent : "GLOBAL",
           type : "namespace",
           elementType : "logical_container"
       } ,         
       {
           localName : "$break",
           fullName : "jbooze.$break",
           summary : "public static variable string $break",
           ref : "logical/jbooze.html#___$break",
           parent : "jbooze",
           type : "variable",
           elementType : "variable"
       } ,         
       {
           localName : "Exception",
           fullName : "jbooze.Exception",
           summary : "class Exception",
           ref : "logical/jbooze/Exception.html",
           parent : "jbooze",
           type : "class",
           elementType : "logical_container"
       } ,         
       {
           localName : "Exception",
           fullName : "jbooze.Exception.Exception",
           summary : "constructor Exception(string messageCode, array params)",
           ref : "logical/jbooze/Exception.html#___Exception",
           parent : "jbooze.Exception",
           type : "constructor",
           elementType : "function"
       } ,         
       {
           localName : "toString",
           fullName : "jbooze.Exception.toString",
           summary : "function toString()",
           ref : "logical/jbooze/Exception.html#___toString",
           parent : "jbooze.Exception",
           type : "function",
           elementType : "function"
       } ,         
       {
           localName : "InvalidArgumentException",
           fullName : "jbooze.InvalidArgumentException",
           summary : "class InvalidArgumentException",
           ref : "logical/jbooze/InvalidArgumentException.html",
           parent : "jbooze",
           type : "class",
           elementType : "logical_container"
       } ,         
       {
           localName : "_closeHooks",
           fullName : "jbooze._closeHooks",
           summary : "variable function()[] _closeHooks",
           ref : "logical/jbooze.html#____closeHooks",
           parent : "jbooze",
           type : "variable",
           elementType : "variable"
       } ,         
       {
           localName : "_global",
           fullName : "jbooze._global",
           summary : "variable object _global",
           ref : "logical/jbooze.html#____global",
           parent : "jbooze",
           type : "variable",
           elementType : "variable"
       } ,         
       {
           localName : "_startupFile",
           fullName : "jbooze._startupFile",
           summary : "variable string _startupFile",
           ref : "logical/jbooze.html#____startupFile",
           parent : "jbooze",
           type : "variable",
           elementType : "variable"
       } ,         
       {
           localName : "addUnloadHook",
           fullName : "jbooze.addUnloadHook",
           summary : "function addUnloadHook(function() func)",
           ref : "logical/jbooze.html#___addUnloadHook",
           parent : "jbooze",
           type : "function",
           elementType : "function"
       } ,         
       {
           localName : "browser",
           fullName : "jbooze.browser",
           summary : "namespace browser",
           ref : "logical/jbooze/browser.html",
           parent : "jbooze",
           type : "namespace",
           elementType : "logical_container"
       } ,         
       {
           localName : "BaseBrowser",
           fullName : "jbooze.browser.BaseBrowser",
           summary : "abstract class BaseBrowser",
           ref : "logical/jbooze/browser/BaseBrowser.html",
           parent : "jbooze.browser",
           type : "class",
           elementType : "logical_container"
       } ,         
       {
           localName : "addListener",
           fullName : "jbooze.browser.BaseBrowser.addListener",
           summary : "function addListener(DOMElement dom, string eventName, function(event) listener, boolean doCapture)",
           ref : "logical/jbooze/browser/BaseBrowser.html#___addListener",
           parent : "jbooze.browser.BaseBrowser",
           type : "function",
           elementType : "function"
       } ,         
       {
           localName : "clearAttributes",
           fullName : "jbooze.browser.BaseBrowser.clearAttributes",
           summary : "function clearAttributes(DOMElement element)",
           ref : "logical/jbooze/browser/BaseBrowser.html#___clearAttributes",
           parent : "jbooze.browser.BaseBrowser",
           type : "function",
           elementType : "function"
       } ,         
       {
           localName : "getAttribute",
           fullName : "jbooze.browser.BaseBrowser.getAttribute",
           summary : "function string getAttribute(DOMElement domNode, string attrName)",
           ref : "logical/jbooze/browser/BaseBrowser.html#___getAttribute",
           parent : "jbooze.browser.BaseBrowser",
           type : "function",
           elementType : "function"
       } ,         
       {
           localName : "getComputedStyle",
           fullName : "jbooze.browser.BaseBrowser.getComputedStyle",
           summary : "function string getComputedStyle(DOMElement element, string styleName)",
           ref : "logical/jbooze/browser/BaseBrowser.html#___getComputedStyle",
           parent : "jbooze.browser.BaseBrowser",
           type : "function",
           elementType : "function"
       } ,         
       {
           localName : "initialize",
           fullName : "jbooze.browser.BaseBrowser.initialize",
           summary : "constructor initialize()",
           ref : "logical/jbooze/browser/BaseBrowser.html#___initialize",
           parent : "jbooze.browser.BaseBrowser",
           type : "constructor",
           elementType : "function"
       } ,         
       {
           localName : "location",
           fullName : "jbooze.browser.BaseBrowser.location",
           summary : "read write property String location",
           ref : "logical/jbooze/browser/BaseBrowser.html#___location",
           parent : "jbooze.browser.BaseBrowser",
           type : "property",
           elementType : "variable"
       } ,         
       {
           localName : "mapCssProperty",
           fullName : "jbooze.browser.BaseBrowser.mapCssProperty",
           summary : "function string mapCssProperty(string property)",
           ref : "logical/jbooze/browser/BaseBrowser.html#___mapCssProperty",
           parent : "jbooze.browser.BaseBrowser",
           type : "function",
           elementType : "function"
       } ,         
       {
           localName : "mapEventName",
           fullName : "jbooze.browser.BaseBrowser.mapEventName",
           summary : "function string mapEventName(string eventName)",
           ref : "logical/jbooze/browser/BaseBrowser.html#___mapEventName",
           parent : "jbooze.browser.BaseBrowser",
           type : "function",
           elementType : "function"
       } ,         
       {
           localName : "overrideMe",
           fullName : "jbooze.browser.BaseBrowser.overrideMe",
           summary : "abstract protected function  overrideMe()",
           ref : "logical/jbooze/browser/BaseBrowser.html#___overrideMe",
           parent : "jbooze.browser.BaseBrowser",
           type : "function",
           elementType : "function"
       } ,         
       {
           localName : "removeListener",
           fullName : "jbooze.browser.BaseBrowser.removeListener",
           summary : "function removeListener(DOMElement dom, string eventName, function(event) listener, boolean doCapture)",
           ref : "logical/jbooze/browser/BaseBrowser.html#___removeListener",
           parent : "jbooze.browser.BaseBrowser",
           type : "function",
           elementType : "function"
       } ,         
       {
           localName : "testVar",
           fullName : "jbooze.browser.BaseBrowser.testVar",
           summary : "private variable int testVar",
           ref : "logical/jbooze/browser/BaseBrowser.html#___testVar",
           parent : "jbooze.browser.BaseBrowser",
           type : "variable",
           elementType : "variable"
       } ,         
       {
           localName : "Explorer",
           fullName : "jbooze.browser.Explorer",
           summary : "class Explorer",
           ref : "logical/jbooze/browser/Explorer.html",
           parent : "jbooze.browser",
           type : "class",
           elementType : "logical_container"
       } ,         
       {
           localName : "addListener",
           fullName : "jbooze.browser.Explorer.addListener",
           summary : "function addListener(DOMElement dom, string eventName, function(event) listener, boolean doCapture)",
           ref : "logical/jbooze/browser/Explorer.html#___addListener",
           parent : "jbooze.browser.Explorer",
           type : "function",
           elementType : "function"
       } ,         
       {
           localName : "clearAttributes",
           fullName : "jbooze.browser.Explorer.clearAttributes",
           summary : "function clearAttributes(DOMElement element)",
           ref : "logical/jbooze/browser/Explorer.html#___clearAttributes",
           parent : "jbooze.browser.Explorer",
           type : "function",
           elementType : "function"
       } ,         
       {
           localName : "getAttribute",
           fullName : "jbooze.browser.Explorer.getAttribute",
           summary : "function getAttribute(DOMElement domNode, string attrName)",
           ref : "logical/jbooze/browser/Explorer.html#___getAttribute",
           parent : "jbooze.browser.Explorer",
           type : "function",
           elementType : "function"
       } ,         
       {
           localName : "getComputedStyle",
           fullName : "jbooze.browser.Explorer.getComputedStyle",
           summary : "function getComputedStyle(DOMElement element, string styleName)",
           ref : "logical/jbooze/browser/Explorer.html#___getComputedStyle",
           parent : "jbooze.browser.Explorer",
           type : "function",
           elementType : "function"
       } ,         
       {
           localName : "initialize",
           fullName : "jbooze.browser.Explorer.initialize",
           summary : "constructor initialize()",
           ref : "logical/jbooze/browser/Explorer.html#___initialize",
           parent : "jbooze.browser.Explorer",
           type : "constructor",
           elementType : "function"
       } ,         
       {
           localName : "removeListener",
           fullName : "jbooze.browser.Explorer.removeListener",
           summary : "function removeListener(DOMElement dom, string eventName, function(event) listener, boolean doCapture)",
           ref : "logical/jbooze/browser/Explorer.html#___removeListener",
           parent : "jbooze.browser.Explorer",
           type : "function",
           elementType : "function"
       } ,         
       {
           localName : "testVar",
           fullName : "jbooze.browser.Explorer.testVar",
           summary : "variable int testVar",
           ref : "logical/jbooze/browser/Explorer.html#___testVar",
           parent : "jbooze.browser.Explorer",
           type : "variable",
           elementType : "variable"
       } ,         
       {
           localName : "KHTML",
           fullName : "jbooze.browser.KHTML",
           summary : "class KHTML",
           ref : "logical/jbooze/browser/KHTML.html",
           parent : "jbooze.browser",
           type : "class",
           elementType : "logical_container"
       } ,         
       {
           localName : "initialize",
           fullName : "jbooze.browser.KHTML.initialize",
           summary : "constructor initialize()",
           ref : "logical/jbooze/browser/KHTML.html#___initialize",
           parent : "jbooze.browser.KHTML",
           type : "constructor",
           elementType : "function"
       } ,         
       {
           localName : "Mozilla",
           fullName : "jbooze.browser.Mozilla",
           summary : "class Mozilla",
           ref : "logical/jbooze/browser/Mozilla.html",
           parent : "jbooze.browser",
           type : "class",
           elementType : "logical_container"
       } ,         
       {
           localName : "initialize",
           fullName : "jbooze.browser.Mozilla.initialize",
           summary : "constructor initialize()",
           ref : "logical/jbooze/browser/Mozilla.html#___initialize",
           parent : "jbooze.browser.Mozilla",
           type : "constructor",
           elementType : "function"
       } ,         
       {
           localName : "overrideMe",
           fullName : "jbooze.browser.Mozilla.overrideMe",
           summary : "public function  overrideMe()",
           ref : "logical/jbooze/browser/Mozilla.html#___overrideMe",
           parent : "jbooze.browser.Mozilla",
           type : "function",
           elementType : "function"
       } ,         
       {
           localName : "Opera",
           fullName : "jbooze.browser.Opera",
           summary : "class Opera",
           ref : "logical/jbooze/browser/Opera.html",
           parent : "jbooze.browser",
           type : "class",
           elementType : "logical_container"
       } ,         
       {
           localName : "addListener",
           fullName : "jbooze.browser.Opera.addListener",
           summary : "function addListener(DOMElement dom, string eventName, function(event) listener, boolean doCapture)",
           ref : "logical/jbooze/browser/Opera.html#___addListener",
           parent : "jbooze.browser.Opera",
           type : "function",
           elementType : "function"
       } ,         
       {
           localName : "initialize",
           fullName : "jbooze.browser.Opera.initialize",
           summary : "constructor initialize()",
           ref : "logical/jbooze/browser/Opera.html#___initialize",
           parent : "jbooze.browser.Opera",
           type : "constructor",
           elementType : "function"
       } ,         
       {
           localName : "removeListener",
           fullName : "jbooze.browser.Opera.removeListener",
           summary : "function removeListener(DOMElement dom, string eventName, function(event) listener, boolean doCapture)",
           ref : "logical/jbooze/browser/Opera.html#___removeListener",
           parent : "jbooze.browser.Opera",
           type : "function",
           elementType : "function"
       } ,         
       {
           localName : "forEach",
           fullName : "jbooze.forEach",
           summary : "function forEach(array arr, iteratorCallback func, boolean backwards)\nforEach(object obj, iteratorCallback func)",
           ref : "logical/jbooze.html#___forEach",
           parent : "jbooze",
           type : "function",
           elementType : "function"
       } ,         
       {
           localName : "isEmpty",
           fullName : "jbooze.isEmpty",
           summary : "function isEmpty(object obj)",
           ref : "logical/jbooze.html#___isEmpty",
           parent : "jbooze",
           type : "function",
           elementType : "function"
       } ,         
       {
           localName : "iteratorCallback",
           fullName : "jbooze.iteratorCallback",
           summary : "ifunction iteratorCallback(item, int index)\niteratorCallback(key, value)",
           ref : "logical/jbooze.html#___iteratorCallback",
           parent : "jbooze",
           type : "ifunction",
           elementType : "function"
       } ,         
       {
           localName : "notImplemented",
           fullName : "jbooze.notImplemented",
           summary : "function notImplemented(string methodName)",
           ref : "logical/jbooze.html#___notImplemented",
           parent : "jbooze",
           type : "function",
           elementType : "function"
       } ,         
       {
           localName : "search",
           fullName : "jbooze.search",
           summary : "function int search(array arr, object item, function (item, arrayItem) comparator)",
           ref : "logical/jbooze.html#___search",
           parent : "jbooze",
           type : "function",
           elementType : "function"
       } ,         
       {
           localName : "toArray",
           fullName : "jbooze.toArray",
           summary : "function array toArray(object data)",
           ref : "logical/jbooze.html#___toArray",
           parent : "jbooze",
           type : "function",
           elementType : "function"
       } ,         
       {
           localName : "jbooze_config",
           fullName : "jbooze_config",
           summary : "struct jbooze_config",
           ref : "logical/jbooze_config.html",
           parent : "GLOBAL",
           type : "struct",
           elementType : "logical_container"
       } ,         
       {
           localName : "debug",
           fullName : "jbooze_config.debug",
           summary : "variable debug",
           ref : "logical/jbooze_config.html#___debug",
           parent : "jbooze_config",
           type : "variable",
           elementType : "variable"
       } ,         
       {
           localName : "logLevel",
           fullName : "jbooze_config.logLevel",
           summary : "variable logLevel",
           ref : "logical/jbooze_config.html#___logLevel",
           parent : "jbooze_config",
           type : "variable",
           elementType : "variable"
       } ,         
       {
           localName : "nologs",
           fullName : "jbooze_config.nologs",
           summary : "variable nologs",
           ref : "logical/jbooze_config.html#___nologs",
           parent : "jbooze_config",
           type : "variable",
           elementType : "variable"
       }     ];
    jgdoc.setData(data);
    
})()
    
